
//=======================================================
//  This code is generated by Terasic System Builder
//=======================================================

module DE0_NANO(

	//////////// CLOCK //////////
	input 		          		CLOCK_50,

	//////////// LED //////////
	output		     [7:0]		LED,

	//////////// KEY //////////
	input 		     [1:0]		KEY,

	//////////// SW //////////
	input 		     [3:0]		SW
);



//=======================================================
//  REG/WIRE declarations
//=======================================================




//=======================================================
//  Structural coding
//=======================================================

wire reset_n,en;
wire[31:0] count;


assign reset_n = KEY[0]; // bas�l� 0, normal 1

assign en = SW[0];

assign LED[4:0] = count[26:22];



counter cntr(CLOCK_50,reset_n,en,count);
	
	
endmodule

module counter(input clk,reset_n,en,
					output reg[31:0] count);
					
// clk 0'dan 1 gecisine : posedge clk
// reset_n 1'den 0'a ge�isine : negedge reset_n

always@(posedge clk or negedge reset_n) // clok 
begin	
	if(!reset_n)  // reset_n active low
	begin  
		// reset_n == 0
		count <= 32'd0;
	end
	else
	begin
		// reset_n == 1
		if(en) 
		begin
			count <= count + 32'd1;
		end
	end
end

endmodule


